[package]
name = "egglog-python"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "egglog_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.1", features = ["extension-module"] }
# egglog = { git = "https://github.com/egraphs-good/egglog", rev = "0f777d6700d860e21137ef2cfbdbe5f7ae31b701" }
egglog = { git = "https://github.com/saulshanabrook/egg-smol", rev = "a3cc0c43b1e40b7a2f0af286bb131a33530dd7e4" }
# egglog = { path = "../egg-smol" }

pyo3-log = "0.8.1"
log = "0.4.17"
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
ordered-float = "*"

[package.metadata.maturin]
name = "egglog.bindings"
