[package]
name = "egglog-python"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "egglog_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.1", features = ["extension-module"] }
# egglog = { git = "https://github.com/egraphs-good/egglog", rev = "c83fc750878755eb610a314da90f9273b3bfe25d" }
egglog = { git = "https://github.com/oflatt/egg-smol", rev = "f6df3ff831b65405665e1751b0ef71c61b025432" }
# egglog = { git = "https://github.com/saulshanabrook/egg-smol", rev = "c01695618ed4de2fbfa8116476e208bc1ca86612" }

pyo3-log = "0.8.1"
log = "0.4.17"
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
ordered-float = "*"

[package.metadata.maturin]
name = "egglog.bindings"

[patch.'https://github.com/egraphs-good/egraph-serialize']

egraph-serialize = { git = "https://github.com/saulshanabrook/egraph-serialize", rev = "8dc11836fdade20bf2b20c5f1e2d75bcd005767d" }
