on:
  workflow_dispatch:
    inputs:
      type:
        description: "Release type"
        required: true
        default: "major"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: python increment_version.py $TYPE
        env:
          TYPE: ${{ inputs.type }}
      - run: git push
      - run: git push --tags
